Glu:
  files:
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/GluGluToContinToZZTo2e2nu_13TeV_MCFM701_pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/GluGluToContinToZZTo2mu2nu_13TeV_MCFM701_pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/GluGluToContinToZZTo4e_13TeV_MCFM701_pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/GluGluToContinToZZTo4mu_13TeV_MCFM701_pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8.root
  type: background
  color: 139
  kfactor: 1
ZZ_EWK:
  files:
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/ZZJJ_ZZTo2L2Nu_EWK_13TeV-madgraph-pythia8.root
  type: signal
  color: 2
  kfactor: 1   
DY:
  files:
  # - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  # - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DY2JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  # - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DY3JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  # - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DY4JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8    
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToLL_M-50_HT-70to100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToLL_M-50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToLL_M-50_HT-600to800_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToLL_M-50_HT-800to1200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToLL_M-50_HT-1200to2500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToLL_M-50_HT-2500toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8.root    
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DYJetsToTauTau_ForcedMuEleDecay_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_ext1.root
  type: background
  color: 901
  kfactor: 1
WZ:
  files:
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/WZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
  type: background
  color: 856
  kfactor: 1
ZZ:
  files:
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/ZZTo2L2Nu_13TeV_powheg_pythia8_ext1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/ZZTo2L2Q_13TeV_amcatnloFXFX_madspin_pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/ZZTo4L_13TeV_powheg_pythia8_ext1.root    
  type: background  
  color: 798
  kfactor: 1
Top:
  files:
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/TTTo2L2Nu_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/TTWJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/TTWJetsToQQ_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/TTZToQQ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root
  type: background
  color: 124
  kfactor: 1
WW:
  files:
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/WWTo2L2Nu_13TeV-powheg.root
  type: background
  color: 842
  kfactor: 1
Data:
  files:
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleEG_Run2016B_ver2-Nano25Oct2019_ver2-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleEG_Run2016C-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleEG_Run2016D-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleEG_Run2016E-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleEG_Run2016F-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleEG_Run2016G-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleEG_Run2016H-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleMuon_Run2016B_ver2-Nano25Oct2019_ver2-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleMuon_Run2016C-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleMuon_Run2016D-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleMuon_Run2016E-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleMuon_Run2016F-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleMuon_Run2016G-Nano25Oct2019-v1.root
  - /afs/cern.ch/work/m/mmittal/private/VBS2l2nu/Plotting/CMSSW_11_0_2/src/WFH2016/merged/DoubleMuon_Run2016H-Nano25Oct2019-v1.root
  type: data
  color: 1
  